apiVersion: v1
kind: Pod
metadata:
  name: ks-pod-env
spec:
  containers:
    - name: ks-pod-env
      image: busybox
      command:
        - sleep
        - "10000"
      env:
        - valueFrom:
            secretKeyRef:
              name: ks-secret-env
              key: config.yml
          name: SECRET_CONFIG
  restartPolicy: Never
  