apiVersion: v1
kind: Pod
metadata:
  name: ks-pod
  namespace: default
spec:
  containers:
    - name: ks-pod
      image: busybox
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: "/etc/ks-path"
          name: ks-path
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: ks-path
      secret:
        secretName: ks-secret-config
        items:
          - key: config.yml
            path: config.yml
            mode: 400
            
          