apiVersion: v1
kind: Service
metadata:
  name: pirate-day-backend-svc
spec:
  type: NodePort
  selector:
    app: pirate-day-backend
  ports:
    - protocol: TCP
      port: 30081
      nodePort: 30081
      targetPort: 3000