apiVersion: v1
kind: Pod
metadata:
  name: pirate-day
  labels:
    app: pirate-day
spec:
  containers:
    - name: pirate-day
      image: simonsatt/pirate-day:0.0.1
      volumeMounts:
        - name: pirate-config
          mountPath: /usr/src/app/.env
          subPath: .env
          readOnly: true
      
  volumes:
    - name: pirate-config
      configMap:
        name: pirate-config
        items:
          - key: .env
            path: .env
            