apiVersion: v1
kind: Pod
metadata:
  name: k8-demo-pod
spec:
  serviceAccount: jenkins
  containers:
    - name: shell
      image: alpine:3.7
      command:
        - "sh"
        - "c"
        - "sleep 10000"